name: Game.cpp build

on: [push]

jobs:
  build_macos:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build objects
        run: clang++ -std=c++17 -Wall -c ./libs/libGame/Game.cpp ./libs/libPlayer/Player.cpp ./libs/libUI/UI.cpp ./src/main.cpp
      
      - name: Link objects
        run: clang++ -std=c++17 -Wall ./*.o -o game
        
  build_windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build objects
        run: cl /Wall /c ./libs/libGame/Game.cpp ./libs/libPlayer/Player.cpp ./libs/libUI/UI.cpp ./src/main.cpp
