name: CMake Build Matrix

on: [push]

jobs:
  build_macos:
    name: Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: clang++ -std=c++17 *.cpp
