name: Build all

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build objects
        run: clang++ -std=c++11 -Wall -c ./libs/libGame/Game.cpp ./libs/libPlayer/Player.cpp ./libs/libUI/UI.cpp ./src/main.cpp
      
      - name: Link objects
        run: clang++ -std=c++11 -Wall ./*.o -o game

  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build objects
        run: g++ -std=c++11 -Wall -c ./libs/libGame/Game.cpp ./libs/libPlayer/Player.cpp ./libs/libUI/UI.cpp ./src/main.cpp
      
      - name: Link objects
        run: g++ -std=c++11 -Wall ./*.o -o game
        
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build objects
        run: cl /std:c++11 /c ./libs/libGame/Game.cpp ./libs/libPlayer/Player.cpp ./libs/libUI/UI.cpp ./src/main.cpp

      - name: Link objects
        run: cl /std:c++11 ./*.obj -o game