name: Build all

on: [push]

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: KyleMayes/install-llvm-action@v1.7.0
      
      - name: Build by makefile
        run: make

  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build by makefile
        run: make linux-release
        
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build objects
        run: cl /std:c++17 /c ./libs/libGame/Game.cpp ./libs/libPlayer/Player.cpp ./libs/libUI/UI.cpp ./src/main.cpp

      - name: Link objects
        run: cl /std:c++17 ./*.obj -o game
