name: CMake

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '.github/workflows/cmake.yml'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: CMake configure
        run: cmake -G "Unix Makefiles" -B ./build .

      - name: CMake build
        run: cmake --build ./build

  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fix LTO
        run: sed -i 's/-flto=full/-flto/g' CMakeLists.txt

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
          
      - name: CMake configure
        run: cmake -G "Unix Makefiles" -B ./build .

      - name: CMake build
        run: cmake --build ./build

  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: CMake configure
        run: cmake -G "Visual Studio 17 2022" -B ./build .

      - name: CMake build
        run: cmake --build ./build
