name: Makefile

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '.github/workflows/makefile.yml'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fix ar
        run: find . -name Makefile -exec sed -i '' "s/llvm-ar/ar/g" {} +

      - name: Make
        run: make
