name: Makefile

on: [push]

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fix ar
        run: sed -i '' "s/llvm-ar/ar/g" Makefile

      - name: Make
        run: make
