name: Makefile

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '.github/workflows/makefile.yml'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make
        run: make AR=ar

  # build_windows:
  #   name: Windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: Copy assets
  #       run: cp ./tests/*.txt ./

  #     - name: Make
  #       cmd: mingw32-make EXE=.exe AR=ar CC=g++ L_FLAG=-llib AR_EXT=lib
