name: Makefile

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**Makefile'
      - '.github/workflows/makefile.yml'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fix ar
        run: find . -name Makefile -exec sed -i '' "s/llvm-ar/ar/g" {} +
      
      - name: Copy assets
        run: cp ./tests/*.txt ./

      - name: Make
        run: make

  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      
      - name: Copy assets
        run: cp ./tests/*.txt ./

      - name: Make
        run: mingw32-make CXXFLAGS="-std=c++14 -Wall" EXE=.exe AR=ar CC=g++ L_FLAG=-llib AR_EXT=lib
