name: Makefile

on: [push]

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make
        run: |
          shopt -s expand_aliases
          alias llvm-ar=ar
          make
