name: Test

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make tests
        run: make test
      
      - name: Runing tests
        run: ./tictactoe-test

  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make tests
        run: make test
      
      - name: Runing tests
        run: ./tictactoe-test
